service: prowess-serverless
app: prowess
org: skstrafer14
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    shouldStartNameWithService: true

functions:
  puuidv2:
    handler: get_puuidv2.main
    events:
      - http:
          path: api/v2/users/{region}/{game_name_with_tagline}
          method: get
          cors: true
          request:
            parameters:
              paths:
                region: true
                game_name_with_tagline: true
  datav2:
    handler: update_and_retrieve_datav2.main
    events:
      - http:
          path: api/v2/data/{session_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                session_id: true
  reset:
    handler: restart_session.main
    events:
      - http:
          path: api/v1/data/restart
          method: put
          cors: true
          request:
            parameters:
              querystrings:
                session_id: true

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-api-gateway-throttling

custom:
  pythonRequirements:
    dockerizePip: true
  dotenv:
    include:
      - CONSUMER_API_URL
      - DISCORD_WEBHOOK
  apiGatewayThrottling:
    maxRequestsPerSecond: 500
    maxConcurrentRequests: 100
