service: prowess-serverless
app: prowess
org: skstrafer14
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    shouldStartNameWithService: true

functions:
  puuid:
    handler: get_puuid.main
    events:
      - http:
          path: api/v1/users/{tagLine}/{gameName}
          method: get
          request:
            parameters:
              paths:
                tagLine: true
                gameName: true
  data:
    handler: update_and_retrieve_data.main
    events:
      - http:
          path: api/v1/data/{puuid}
          method: post
          request:
            parameters:
              querystrings:
                session_id: false
                region: true
              paths:
                puuid: true

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-api-gateway-throttling

custom:
  pythonRequirements:
    dockerizePip: true
  dotenv:
    include:
      - CONSUMER_API_URL
      - DISCORD_WEBHOOK
  apiGatewayThrottling:
    maxRequestsPerSecond: 500
    maxConcurrentRequests: 100
